// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UGHHkxWkqPapECVIADpb_6uiUnsS6Z4',
    appId: '1:117021162459:web:0f6d5bdbb97cc5c28485fe',
    messagingSenderId: '117021162459',
    projectId: 'oneshop-aec38',
    authDomain: 'oneshop-aec38.firebaseapp.com',
    storageBucket: 'oneshop-aec38.appspot.com',
    measurementId: 'G-DTBZKD1N5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8qaBvEXcF7RzIrMvmUIEwcmwIGs76YsA',
    appId: '1:117021162459:android:3a87694cae3c50018485fe',
    messagingSenderId: '117021162459',
    projectId: 'oneshop-aec38',
    storageBucket: 'oneshop-aec38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAHM9ZWTnPSc2SuVCG07PAwhNHUu21k-U',
    appId: '1:117021162459:ios:413c66d0ca4379838485fe',
    messagingSenderId: '117021162459',
    projectId: 'oneshop-aec38',
    storageBucket: 'oneshop-aec38.appspot.com',
    iosClientId:
        '117021162459-ttgfuog0u7bla9m803hi1q75jacgi8gr.apps.googleusercontent.com',
    iosBundleId: 'com.example.playground',
  );
}
